import { createSlice } from '@reduxjs/toolkit';

const calendarBooking = createSlice({
  name: 'calendarBooking',
  initialState: {
    bookedDate: null
  },
  reducers: {
    setBookedDate: (state, action) => {
      state.bookedDate = action.payload; // Update the treatmentType with the payload
    }
  }
});

export const { setBookedDate } = calendarBooking.actions;
// Extract the action creators generated by the treatments slice
export default calendarBooking.reducer;
