/* eslint-disable max-len */
import { createSlice } from '@reduxjs/toolkit';

// Create a slice of the Redux store for user
const user = createSlice({
  name: 'user', // Name of the slice
  initialState: {
    userId: null,
    accessToken: null,
    error: null,
    firstName: null, // Add firstName property
    lastName: null, // Add lastName property
    mobilePhone: null, // Add mobilePhone property
    email: null, // Add email property
    pickedDate: null // Add pickedDate property
  },
  reducers: {
    setUserId: (state, action) => {
      state.userId = action.payload; // Update the userId with the payload
    },
    setFirstName: (state, action) => {
      state.firstName = action.payload; // Update the firstName with the payload
    },
    setLastName: (state, action) => {
      state.lastName = action.payload; // Update the lastName with the payload
    },
    setMobilePhone: (state, action) => {
      state.mobilePhone = action.payload; // Update the mobilePhone with the payload
    },
    setEmail: (state, action) => {
      state.email = action.payload; // Update the email with the payload
    },
    setAccessToken: (state, action) => {
      state.accessToken = action.payload; // Update the accessToken with the payload
    },
    setError: (state, action) => {
      state.error = action.payload; // Update the error with the payload
    },
    setPickedDate: (state, action) => {
      state.pickedDate = action.payload; // Update the pickedDate with the payload
    },
    loginSuccess: (state, action) => {
      const { accessToken } = action.payload;
      state.accessToken = accessToken;

      // Store the access token in local storage
      localStorage.setItem('accessToken', accessToken);
    },
    logout: (state) => {
      state.userId = null; // Clear the userId
      state.email = null; // Clear the email
      state.accessToken = null; // Clear the accessToken
      state.pickedDate = null; // Clear the pickedDate
      localStorage.removeItem('accessToken'); // Remove access token from local storage
    }
  }
});

// Extract the action creators generated by the user slice
export const {
  setUserId,
  setFirstName,
  setLastName,
  setAccessToken,
  setMobilePhone,
  setEmail,
  setError,
  setPickedDate, // Add setPickedDate action
  loginSuccess,
  logout
} = user.actions;

export default user; // Export the user slice as the default export
